<?php
/**
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@vv0lll.com so we can send you a copy immediately.
 *
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @author		Thanh Dancer - dancer.thanh@gmail.com
 * @since			1.0
 * @version		$Id: addArticle.phtml  1/25/15 3:23 PM lion $
 */

 ?>
<h2><?=$pageTitle?></h2>
<hr />
<br/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Article Content
        </div>
    </div>
    <div class="panel-body">
        <form enctype="multipart/form-data" role="form" method="post" class="validate">
            <div class="form-group">
                <label class="control-label">Project category</label>
                <select class="form-control" name="categoryid">
                    <option>Choose a Category</option>
                    <?php
                    foreach($categories['items'] as $category):
                        ?>

                        <option value="<?=$category['categoryid']?>"><?=str_repeat('---', $category['depth']) . ' '.  $category['name']?></option>
                    <?php
                    endforeach;
                    ?>
                </select>
            </div>

            <div class="form-group">
                <label class="control-label">Title</label>
                <input type="text" value="<?=set_value('title')?>" class="form-control" name="title" placeholder="Title" />
            </div>


            <div class="row form-group">
                <div class="col-md-9">
                    <label class="control-label">Sapo</label>
                    <textarea style="height: 150px" name="sapo" class="form-control"><?=set_value('sapo')?></textarea>
                </div>
                <div class="col-md-3">

                    <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;" data-trigger="fileinput">
                            <img src="http://placehold.it/150&text=Thumbnail" alt="Project thumbnail">
                        </div>
                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 150px; max-height: 150px"></div>
                        <div>
									<span class="btn btn-white btn-file">
										<span class="fileinput-new">Select image</span>
										<span class="fileinput-exists">Change</span>
										<input type="file" name="thumb" accept="image/*">
									</span>
                            <a href="#" class="btn btn-orange fileinput-exists" data-dismiss="fileinput">Remove</a>
                        </div>
                    </div>
                </div>

            </div>



            <div class="form-group">
                <textarea data-validate="required" name="content" id="content" rows="20" class="form-control"><?=set_value('projectcontent')?></textarea>
            </div>

            <div class="row form-group">

                <div class="col-md-4">
                    <label class="control-label">Publish date</label>
                    <input data-mask="date" value="<?=set_value('date')?>" class="form-control" data-validate="required" name="publishdate" placeholder="dd/mm/yyyy" />
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Status</label>
                        <select class="form-control" name="status">
                            <option value="2">Enabled</option>
                            <option value="0">Disabled</option>
                            <option value="1">Pending</option>
                        </select>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Hot article</label>
                        <select class="form-control" name="hot">
                            <option value="0">No</option>
                            <option value="1">Yes</option>
                        </select>
                    </div>
                </div>


            </div>



            <div class="form-group">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-success">Save</button>
                    <button type="reset" class="btn btn-primary">Reset</button>
                </div>
            </div>

        </form>
    </div>

</div>

<script>
    $(document).ready(function(){
        // Rich editor
        tinymce.init({
            selector: "#content",
            theme: "modern",
            plugins: [
                "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                "save table contextmenu directionality emoticons template paste textcolor responsivefilemanager"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons | responsivefilemanager | ",



            external_filemanager_path:"/assets/filemanager/",
            filemanager_title:"Nhandan.edu.vn" ,
            filemanager_access_key:'bgB65j4AUmDs5cR84s3ZnJdvv9DQYxVZBRk2bzNn7HfDL4jRkXnFjyJksJJWH23Wvq249XV3hxTywEX5FVx4KEqbMyVh',
            external_plugins: { "filemanager" : "/assets/filemanager/plugin.min.js"}
        });


    });

</script>