<div class="sidebar-menu">


<header class="logo-env">

    <!-- logo -->
    <div class="logo">
        <a href="<?php echo base_url(); ?>">
            <img src="<?php echo base_url(); ?>assets/images/logo@2x.png" width="120" alt="" />
        </a>
    </div>

    <!-- logo collapse icon -->

    <div class="sidebar-collapse">
        <a href="#" class="sidebar-collapse-icon with-animation"><!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition -->
            <i class="entypo-menu"></i>
        </a>
    </div>



    <!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
    <div class="sidebar-mobile-menu visible-xs">
        <a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
            <i class="entypo-menu"></i>
        </a>
    </div>

</header>






<ul id="main-menu" class="auto-inherit-active-class">
<!-- add class "multiple-expanded" to allow multiple submenus to open -->
<!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->

<!-- Search Bar -->
<!--
<li id="search">
    <form method="get" action="">
        <input type="text" name="q" class="search-input" placeholder="Search something..."/>
        <button type="submit">
            <i class="entypo-search"></i>
        </button>
    </form>
</li>
-->
    <!-- Default menu -->
    <li>
        <a href="<?php echo site_url('admin/user/edit/' . $this->session->userdata('userid')); ?>">
            <img class="img-circle" width="30" src="<?php echo ($this->session->userdata('avatar') != '') ? $this->session->userdata('avatar') : base_url() . '/assets/images/default-avatar.png'; ?>" />
            <span><strong><?php echo $this->session->userdata('firstname') . " " . $this->session->userdata('lastname'); ?></strong></span>
        </a>
        <ul>
            <li>
                <a href="<?php echo site_url('admin/user/edit/' . $this->session->userdata('userid')); ?>">
                    <span>Edit info</span>
                </a>
            </li>
            <li>
                <a href="<?php echo site_url('admin/user/logout/'); ?>">
                    <span>Logout</span>
                </a>
            </li>
        </ul>
    </li>

    <!--/ Default menu -->

    <!-- Addition menus -->
    <?php 
    foreach($this->config->config['adminMenu'] as $menus):
    if(!in_array($this->session->userdata('group'), explode(',', $menus['visibility']))) continue;
    ?>
    <li>
        <a href="<?=site_url($menus['route'])?>">
            <i class="<?=$menus['icon']?>"></i>
            <span><?=$menus['title']?></span>
        </a>
        <?php if(isset($menus['sub']) && is_array($menus['sub'])):?>
        <ul>
            <?php
            foreach($menus['sub'] as $sub1):
            if(!in_array($this->session->userdata('group'), explode(',', $sub1['visibility']))) continue;
            ?>
            <li <?php echo (('admin/' . $this->uri->segment(2) . '/' . $this->uri->segment(3)) == $sub1['route'] || ('admin/' . $this->uri->segment(2) ) == $sub1['route']) ? 'class="active"' : ''; ?>>
                <a href="<?=site_url($sub1['route'])?>">
                    <i class="<?=$sub1['icon']?>"></i>
                    <span><?=$sub1['title']?></span>
                </a>
                <?php if(isset($sub1['sub']) && is_array($sub1['sub'])):?>
                <ul>
                    <?php
                    foreach($sub1['sub'] as $sub2):
                    if(!in_array($this->session->userdata('group'), explode(',', $sub2['visibility']))) continue;
                    ?>
                    <li <?php echo (('admin/' . $this->uri->segment(2) . '/' . $this->uri->segment(3)) == $sub2['route']); ?>>
                        <a href="<?=site_url($sub2['route'])?>">
                            <i class="<?=$sub2['icon']?>"></i>
                            <span><?=$sub2['title']?></span>
                        </a>
                    </li>
                    <?php
                    endforeach;
                    ?>
                </ul>
                <?php endif; ?>
            </li>
            <?php
            endforeach;
            ?>
        </ul>
        <?php endif; ?>
    </li>
    <?php
    endforeach;
    ?>
    <!--/ Addition menus -->


</ul>

</div>
 