<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo $title; ?></title>
<link href="<?php echo base_url();?>/assets/frontend/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo base_url();?>/assets/frontend/css/style.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<script type="text/javascript" src="<?php echo base_url();?>/assets/js/jquery-1.11.0.min.js"></script>
<script type="text/javascript"  src="<?php echo base_url();?>/assets/frontend/js/jssor.slider.mini.js"></script>
<script type="text/javascript" src="<?=base_url()?>/assets/js/fushioncharts/js/fusioncharts.js"></script>
<script type="text/javascript" src="<?=base_url()?>/assets/js/fushioncharts/js/themes/fusioncharts.theme.fint.js"></script>
