<div class="sidebar-menu">


<header class="logo-env">

    <!-- logo -->
    <div class="logo">
        <a href="<?php echo base_url(); ?>">
            <img src="<?php echo base_url(); ?>assets/images/logo@2x.png" width="120" alt="" />
        </a>
    </div>

    <!-- logo collapse icon -->

    <div class="sidebar-collapse">
        <a href="#" class="sidebar-collapse-icon with-animation"><!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition -->
            <i class="entypo-menu"></i>
        </a>
    </div>



    <!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->
    <div class="sidebar-mobile-menu visible-xs">
        <a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->
            <i class="entypo-menu"></i>
        </a>
    </div>

</header>






<ul id="main-menu" class="">
<!-- add class "multiple-expanded" to allow multiple submenus to open -->
<!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->

<!-- Search Bar -->
<!--
<li id="search">
    <form method="get" action="">
        <input type="text" name="q" class="search-input" placeholder="Search something..."/>
        <button type="submit">
            <i class="entypo-search"></i>
        </button>
    </form>
</li>
-->
    <li>
        <a href="<?php echo site_url('/user/edit/' . $this->session->userdata('userid')); ?>">
            <img class="img-circle" width="30" src="<?php echo ($this->session->userdata('avatar') != '') ? $this->session->userdata('avatar') : base_url() . '/assets/images/default-avatar.png'; ?>" />
            <span><strong><?php echo $this->session->userdata('firstname') . " " . $this->session->userdata('lastname'); ?></strong></span>
        </a>
        <ul>
            <li>
                <a href="<?php echo site_url('/user/edit/' . $this->session->userdata('userid')); ?>">
                    <span>Edit info</span>
                </a>
            </li>
            <li>
                <a href="<?php echo site_url('/user/logout/'); ?>">
                    <span>Logout</span>
                </a>
            </li>
        </ul>
    </li>
    <li>
        <a href="<?=site_url('/project/')?>">
            <i class="entypo-globe"></i>
            <span>Project</span>
        </a>
        <ul>
            <li>
                <a href="<?=site_url('/project/adminMain')?>">
                    <span>List projects</span>
                </a>
            </li>
            <li>
                <a href="<?=site_url('/project/adminAdd')?>">
                    <span>Add project</span>
                </a>
            </li>
            <li>
                <a href="<?=site_url('/project/adminConfig')?>">
                    <span>Config</span>
                </a>
            </li>

        </ul>
    </li>
    <li>
        <a href="<?php echo site_url('/')?>">
            <i class="entypo-cog"></i>
            <span>Administrator</span>
        </a>
        <ul>
            <li>
                <a href="<?php echo site_url('/user/'); ?>">
                    <i class="entypo-user"></i>
                    <span>User</span>
                </a>
                <ul>
                    <li>
                        <a href="<?php echo site_url('/user/display'); ?>">
                            <span>List users</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo site_url('/user/add'); ?>">
                            <span>Add user</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="<?php echo site_url('/permission/'); ?>">
                    <i class="entypo-lock"></i>
                    <span>Permission</span>
                </a>
            </li>
            <li>
                <a href="<?php echo site_url('/setting/'); ?>">
                    <i class="entypo-tools"></i>
                    <span>Setting</span>
                </a>
            </li>
        </ul>
    </li>

</ul>

</div>
 