<script>
    $(document).ready(function(){
        FusionCharts.ready(function () {
            var salesByState = new FusionCharts({
                "type": "maps/vietnam",
                "renderAt": "project_map",
                "width": "100%",
                "height": "100%",
                "dataFormat": "json",
                "dataSource": {
                    "chart": {
                        "bgimagealpha": "0",
                        "caption": "Project map",
                        "subcaption": "Group number of projects by location",
                        "entityFillHoverColor": "#cccccc",
                        "formatNumberScale":"0",
                        "numberScaleValue": "1,1000,1000",
                        "numberScaleUnit": "K,M,B",
                        "showLabels": "0",
                        "theme": "fint"
                    },
                    "colorrange": {
                        "color": [
                            {
                                "minvalue": "1",
                                "maxvalue": "5",
                                "code": "#00ffff"
                            },
                            {
                                "minvalue": "6",
                                "maxvalue": "10",
                                "code": "#00ff19"
                            },
                            {
                                "minvalue": "11",
                                "maxvalue": "20",
                                "code": "#dbff00"
                            },
                            {
                                "minvalue": "21",
                                "maxvalue": "50",
                                "code": "#f9ff00"
                            },
                            {
                                "minvalue": "51",
                                "maxvalue": "100",
                                "code": "#ff8900"
                            },
                            {
                                "minvalue": "101",
                                "maxvalue": "10000",
                                "displayValue": "> 100",
                                "code": "#ff0000"
                            }
                        ]
                    },
                    "data": [

                        <?php
                        foreach($map as $value){
                            echo
                            '{
                                "id" : "' . $value->location . '",
                                "value" : "' . $value->total. '"
                            },';

                        }
                        ?>

                    ]
                },
                "events":{
                    "entityClick": function (evt, data) {

                        window.location = '<?php echo site_url('/projects');?>/' + data.id.toUpperCase();

                    }
                }
            });
            salesByState.render();
        });
    });
</script>

<div class="header">
        <div class="container_top">
            <div class="wrap_landing_and_text">
                <div class="content_top">
                    <div class="wrapper" id="wrap_only_header">
                        <div class="left_content_inner">
                            <div class="left_content">
                                <p class="sub_title_content_inner">
                                    Hệ thống Cơ sở dữ liệu giáo dục
                                </p>
                                <h1 class="main_title_content_inner">
                                    Trường học nhân dân
                                </h1>
                                <p class="detail_content_inner">
                                    được thực hiện bởi Trung tâm Công nghệ Giáo dục DoTank, trực thuộc TW Hội Khuyến học Việt Nam là dự án xã hội hóa giúp kết nối, trao đổi thông tin giữa một bên là các cơ sở giáo dục cần hỗ trợ về cơ sở vật chất, kinh phí hoạt động và một bên là những tổ chức, cá nhân có mong muốn và khả năng hỗ trợ.
                                </p>
                                <div class="button_box_content_inner">
                                    <a href="#" id="button_content_inner">
                                        <span>Tìm hiểu thêm</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <!-- end of left_content_inner -->
                        <div class="right_content_inner">
                            <div class="right_content">
                                <!-- Show vietnam map -->
                                <div id="project_map">
                                </div>
                                    <!-- end of another_box -->

                                <!-- end of detail_content_box -->
                            </div>
                            <!-- end of right_content -->
                        </div>
                        <!-- end of right_content_inner -->
                    </div>
                </div>
                <!-- end of content_top -->
                <div class="landing">
                    <div class="shadow_image">
                    </div>
                    <div class="image_header_container">
                        <img src="<?=base_url()?>/assets/frontend/images/featured_image.jpg" alt="feature_image">
                    </div>
                </div>
                <!-- end of landing -->
            </div>
            <!-- end of wrap_landing_and_text -->
        </div>
        <!-- end of container_top -->
    </div>
    <!-- end of header -->
    <div class="all_projects">
        <div class="wrapper">
            <h1 class="title_of_projects">
                các dự án
            </h1>
            <div class="content_filter_projects">
                <div class="wrap_the_notation_and_decoration">
                    <p class="notation_projects">
                        <a href="#" title="dự án nổi bật">
                            Dự án nổi bật
                        </a>
                    </p>
                    <div class="wrap_the_decoration_container">
                        <div class="container_of_decoration_line">
                            <div class="decoration_line_projects">
                            </div>
                        </div>
                    </div>
                    <p class="find_more_projects">
                        <a href="#" title="tìm thêm">
                            Tìm thêm
                        </a>
                    </p>
                </div>
            </div>
            <!-- end of content_filter_projects -->
            <?php foreach($highlight as $project_2light): ?>

            <div class="content_project">
                <div class="content_project_inner">
                    <img style="max-width: 415px" src="<?=base_url().$project_2light->imgthumb?>" alt="<?=$project_2light->projectname?>" title="<?=$project_2light->projectname?>">
                    <div class="featured_project_content">
                        <div class="feature_project_content_inner">
                            <div class="text_upper_project_content">
                                <h2 class="article_title">
                                    <?=$project_2light->title?>
                                </h2>
                                <p class="article_content">
                                    <?=$project_2light->sapo?>
                                </p>
                            </div>
                            <div class="detail_of_upper_project_content">
                                <div class="left_index_detail">
                                    <a href="#" class="nav_to_location" title="<?=$project_2light->address?>, <?=isset($province[$project_2light->location]) ? $province[$project_2light->location] : $project_2light->location?>">
                                        <p class="location_artical">
                                            <?=$project_2light->address?>, <?=isset($province[$project_2light->location]) ? $province[$project_2light->location] : $project_2light->location?>
                                        </p>
                                    </a>
                                    <meter id="article_meter" value="<?=ceil($project_2light->total * 100 / $project_2light->goal)?>" min="0" max="100">
                                        còn <?=ceil(($project_2light->deadline - time())/86400)?> ngày
                                    </meter>
                                    <table class="index_content">
                                        <tr class="upper_row_content">
                                            <td><?=ceil($project_2light->total * 100 / $project_2light->goal)?>%</td>
                                            <td><?=ceil(($project_2light->deadline - time())/86400)?> ngày</td>
                                            <td><?=number_format($project_2light->total)?></td>
                                        </tr>
                                        <tr class="lower_row_content">
                                            <td>toàn bộ</td>
                                            <td>còn lại</td>
                                            <td>đã nhận</td>
                                        </tr>
                                    </table>
                                </div>
                                <a href="#" class="right_index_detail" title="tài trợ">
                                        <span class="donor_button">
                                        Tài trợ
                                        </span>
                                </a>
                            </div>
                            <!-- end of detail_of_upper_project_content -->
                        </div>
                        <!-- end of feature_project_content_inner -->
                    </div>
                    <!-- end of featured_project_content -->
                </div>
                <!-- end of content_project_inner -->
            </div>
            <!-- end of content_project -->
            <?php endforeach;?>
            <div class="content_filter_projects2">
                <div class="wrap_the_notation_and_decoration">
                    <p class="notation_projects">
                        <a href="#" title="dự án nổi bật">
                            Dự án gấp rút
                        </a>
                    </p>
                    <div class="wrap_the_decoration_container">
                        <div class="container_of_decoration_line">
                            <div class="decoration_line_projects">
                            </div>
                        </div>
                    </div>
                    <p class="find_more_projects">
                        <a href="#" title="tìm thêm">
                            Tìm thêm
                        </a>
                    </p>
                </div>
            </div>
            <!-- end of content_filter_projects -->
        </div>
        <!-- end of wrapper-->
        <div class="urgent_projects">
            <!--<div class="button_urgent_holder">
                <button id="left_click_urgent_projects">
                    <img src="<?=base_url()?>/assets/frontend/images/left_urgent.png">
                </button>
                <button id="right_click_urgent_projects">
                    <img src="<?=base_url()?>/assets/frontend/images/right_urgent.png">
                </button>
            </div>-->
            <div class="hold_content_urgent_projects">
                <div class="wrapper" id="blacken_test">
                    <div id="urgent_slider_container" style="position: relative; top: 0px; left: 0px; width: 1060px; height: 550px; overflow: hidden; ">
                        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1060px; height: 550px;
            overflow: hidden;" >
                            <?php
                            $i = 0;
                            foreach($urgent as $project_urgent):
                                if($i == 0 || $i % 4 == 0){
                                    echo '<div>';
                                }

                                ?>
                                <div class="col_urgent">
                                    <a href="#">
                                        <img style="max-width: 225px; height: 170px" src="<?=base_url().$project_urgent->imgthumb?>">
                                        <h4 style="height: 40px;"><?=$project_urgent->title?></h4>
                                    </a>
                                    <p style="height: 100px; overflow: hidden; margin-bottom: 5px"><?=$project_urgent->sapo?></p>
                                    <div class="index_container">
                                        <div class="urgent_index_detail">
                                            <a href="#" class="nav_to_location" title="<?=$project_urgent->address?>, <?=isset($province[$project_urgent->location]) ? $province[$project_urgent->location] : $project_urgent->location?>">
                                                <p class="location_artical text_urgent">
                                                    <?=$project_urgent->address?>, <?=isset($province[$project_urgent->location]) ? $province[$project_urgent->location] : $project_urgent->location?>
                                                </p>
                                            </a>
                                            <meter class="urgent_meter" value="<?=ceil($project_urgent->total * 100 / $project_urgent->goal)?>" min="0" max="100">
                                                còn 19 ngày
                                            </meter>
                                            <table class="index_content">
                                                <tr class="upper_row_content">
                                                    <td><?=ceil($project_urgent->total * 100 / $project_urgent->goal)?>%</td>
                                                    <td><?=ceil(($project_urgent->deadline - time())/86400)?> ngày</td>
                                                    <td><?=number_format($project_urgent->total)?> </td>
                                                </tr>
                                                <tr class="lower_row_content">
                                                    <td>toàn bộ</td>
                                                    <td>còn lại</td>
                                                    <td>đã nhận</td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                                <!-- End of col_urgent <?=$i + 1 ?> -->
                            <?php
                                if($i == (count($urgent) - 1) || $i % 4 == 3 ){
                                    echo "</div><!-- End block -->";
                                }
                                $i++;
                                endforeach;
                            ?>
                        </div>
                        <!-- Bullet Navigator Skin Begin -->
                        <style>
                            /* jssor slider bullet navigator skin 18 css */
                            /*
                            .jssorb18 div           (normal)
                            .jssorb18 div:hover     (normal mouseover)
                            .jssorb18 .av           (active)
                            .jssorb18 .av:hover     (active mouseover)
                            .jssorb18 .dn           (mousedown)
                            */
                            .jssorb18 div, .jssorb18 div:hover, .jssorb18 .av
                            {
                                background: url(<?=base_url()?>/assets/frontend/images/b18.png) no-repeat;
                                overflow:hidden;
                                cursor: pointer;
                            }
                            .jssorb18 div { background-position: -3px -3px; }
                            .jssorb18 div:hover, .jssorb18 .av:hover { background-position: -33px -3px; }
                            .jssorb18 .av { background-position: -63px -3px; }
                            .jssorb18 .dn, .jssorb18 .dn:hover { background-position: -93px -3px; }

                            .jssorb18 .n
                            {
                                display: none;
                                color: #000;
                            }
                            .jssorb18 div:hover .n, .jssorb18 .av .n, .jssorb18 .av:hover .n, .jssorb18 .dn .n { display: block; }
                        </style>
                        <!-- bullet navigator container -->
                        <div u="navigator" class="jssorb18" style="position: absolute; bottom: 16px; right: 6px;">
                            <!-- bullet navigator item prototype -->
                            <div u="prototype" style="position: absolute; width: 24px; height: 24px; text-align: center;
                line-height: 24px; font-size: 16px;">
                                <div u="numbertemplate" class=n></div>
                            </div>
                        </div>
                        <!-- Bullet Navigator Skin End -->
                    </div>


                </div>
                <!-- end of col_urgent -->
            </div><!--
            <div class="selection_urgent">
                <ul>
                    <li class="active_urgent">
                        <a href="#">1</a>
                    </li>
                    <li class="">
                        <a href="#">2</a>
                    </li>
                    <li class="">
                        <a href="#">3</a>
                    </li>
                    <li class="">
                        <a href="#">4</a>
                    </li>
                </ul>
            </div>
            <!-- end of wrapper -->
        </div>
    </div>
    <!-- end of all_projects -->
    <div class="top_donors">
        <div class="wrapper">
            <h1 class="title_of_projects">
                Các nhà tài trợ nổi bật
            </h1>
        </div>
        <div class="slide_influences">
            <div class="izuxciquwe9834u">
                <div class="wrap_span_izuxciquwe9834u">
                    <div id="slider1_container" style="position: relative; top: 0px; left: 100px; width: 900px; height: 100px; overflow: hidden; ">
                        <!-- Loading Screen -->
                        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
                            <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                background-color: #000; top: 0px; left: 0px;width: 100%;height:100%;">
                            </div>
                            <div style="position: absolute; display: block; background: url(<?=base_url()?>/assets/frontend/images/loading.gif) no-repeat center center;
                top: 0px; left: 0px;width: 100%;height:100%;">
                            </div>
                        </div>

                        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 900px; height: 100px; overflow: hidden;">
                        <?php foreach($sponsors as $sponsor): ?>
                            <div><img u="image" alt="<?=$sponsor->sponsorname?>" src="<?=$sponsor->sponsorlogo?>" /></div>
                        <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- end of top_donors -->
    <script>

        jQuery(document).ready(function ($) {
            var options = {
                $BulletNavigatorOptions: {                                //[Optional] Options to specify and enable navigator or not
                    $Class: $JssorBulletNavigator$,                       //[Required] Class to create navigator instance
                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always
                    $AutoCenter: 1,                                  //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
                    $SpacingX: 0                                   //[Optional] Horizontal space between each item in pixel, default value is 0
                }
            };

            var urgent_slider = new $JssorSlider$("urgent_slider_container", options);

            //responsive code begin
            //you can remove responsive code if you don\'t want the slider scales while window resizes
            function ScaleSlider() {
                var parentWidth = urgent_slider.$Elmt.parentNode.clientWidth;
                if (parentWidth) {
                    var sliderWidth = parentWidth;

                    //keep the slider width no more than 800
                    sliderWidth = Math.min(sliderWidth, 1060);

                    urgent_slider.$ScaleWidth(sliderWidth);
                }
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            //ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>
    <script>
        jQuery(document).ready(function ($) {
            var options = {
                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $AutoPlaySteps: 1,                                  //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1
                $AutoPlayInterval: 0,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
                $PauseOnHover: 4,                               //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

                $ArrowKeyNavigation: true,   			            //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
                $SlideEasing: $JssorEasing$.$EaseLinear,          //[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad
                $SlideDuration: 1600,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
                $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20
                $SlideWidth: 100,                                   //[Optional] Width of every slide in pixels, default value is width of \'slides\' container
                //$SlideHeight: 100,                                //[Optional] Height of every slide in pixels, default value is height of \'slides\' container
                $SlideSpacing: 100, 					                //[Optional] Space between each slide in pixels, default value is 0
                $DisplayPieces: 5,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
                $ParkingPosition: 0,                              //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
                $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
                $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
                $DragOrientation: 1                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
            };

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);

            //responsive code begin
            //you can remove responsive code if you don\'t want the slider scales while window resizes
            function ScaleSlider() {
                var bodyWidth = document.body.clientWidth;
                if (bodyWidth)
                    jssor_slider1.$ScaleWidth(Math.min(bodyWidth, 900));
                else
                    window.setTimeout(ScaleSlider, 30);
            }
            ScaleSlider();

            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>