<?php
/**
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@vv0lll.com so we can send you a copy immediately.
 * 
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @author		Thanh Dancer - dancer.thanh@gmail.com
 * @since			1.0
 * @version		$Id: edit.phtml  12/7/14 2:22 PM lion $
 */
 
 ?>
<h2><?=$pageTitle?></h2>
<hr />
<br/>
<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Project infomation
        </div>
    </div>
    <div class="panel-body">
        <form enctype="multipart/form-data" role="form" method="post" class="validate">
            <div class="form-group">
                <label class="control-label">Project name</label>
                <input type="text" data-validate="required" class="form-control" name="projectname" placeholder="Project name" value="<?=htmlspecialchars($project->projectname)?>" />
            </div>

            <div class="form-group">
                <label class="control-label">Title</label>
                <input type="text" class="form-control" name="title" placeholder="Title" value="<?=htmlspecialchars($project->title)?>" />
            </div>

            <div class="row form-group">
                <div class="col-md-4">
                    <label class="control-label">Goal</label>
                    <input id="goal" type="text" data-validate="required" class="form-control" name="goal" placeholder="Goal (VND)" value="<?=$project->goal?>" />
                </div>
                <div class="col-md-4">
                    <label class="control-label">Deadline</label>
                    <input data-mask="date" class="form-control" data-validate="required" name="deadline" placeholder="dd/mm/yyyy" value="<?=date('d/m/Y', $project->deadline)?>" />
                </div>
                <div class="col-md-4">
                    <label class="control-label">Location</label>
                    <input type="text" class="form-control" data-validate="required" name="location" placeholder="Project location" value="<?=htmlspecialchars($project->location)?>" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-9">
                    <label class="control-label">Sapo</label>
                    <textarea style="height: 150px" name="sapo" class="form-control"><?=htmlspecialchars($project->sapo)?></textarea>
                </div>
                <div class="col-md-3">

                    <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;" data-trigger="fileinput">
                            <img src="<?=base_url().$project->imgthumb?>" alt="Project thumbnail">
                        </div>
                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 150px; max-height: 150px"></div>
                        <div>
									<span class="btn btn-white btn-file">
										<span class="fileinput-new">Select image</span>
										<span class="fileinput-exists">Change</span>
										<input type="file" name="thumb" accept="image/*">
									</span>
                            <a href="#" class="btn btn-orange fileinput-exists" data-dismiss="fileinput">Remove</a>
                        </div>
                    </div>
                </div>

            </div>



            <div class="form-group">
                <textarea data-validate="required" name="projectcontent" id="content" rows="20" class="form-control"><?=$project->content?></textarea>
            </div>

            <div class="form-group">
                <label class="control-label">Status</label>
                <select class="form-control" name="status">
                    <option <?=$project->status == 2 ? 'selected' : '' ?>value="2">Enabled</option>
                    <option <?=$project->status == 0 ? 'selected' : '' ?> value="0">Disabled</option>
                    <option <?=$project->status == 1 ? 'selected' : '' ?> value="1">Pending</option>
                </select>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-success">Save</button>
                    <button type="reset" class="btn btn-primary">Reset</button>
                    <input type="hidden" name="projectid" value="<?=$project->projectid?>" />
                </div>
            </div>

        </form>
    </div>

</div>

<script>
    $(document).ready(function(){
        tinymce.init({
            selector: "#content",
            theme: "modern",
            plugins: [
                "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                "save table contextmenu directionality emoticons template paste textcolor"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons",

        });

        $("#goal").inputmask("999.999.999.999 VND", 'decimal', { alias: "currency" });
    });

</script>