<?php
/**
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@vv0lll.com so we can send you a copy immediately.
 * 
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @author		Thanh Dancer - dancer.thanh@gmail.com
 * @since			1.0
 * @version		$Id: list.phtml  12/7/14 1:44 PM lion $
 */

 ?>

<h2><?=$pageTitle?></h2>
<br />

<table class="table table-bordered datatable" id="listProject">
    <thead>
        <tr>
            <th>Project name</th>
            <th>Thumbnail</th>
            <th>Backers</th>
            <th>Goal</th>
            <th>Deadline</th>
            <th>Location</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($projects as $project): ?>
        <tr>
            <td><?=$project->projectname?></td>
            <td><img src="<?=base_url() . $project->imgthumb?>" alt="<?=$project->projectname?>" style="max-width: 100px; max-height: 100px"/></td>
            <td><a href="<?=site_url('admin/project/backers/' . $project->projectid)?>"><span class="badge <?php echo $project->numbacker > 0 ? "badge-success" : ''?>"><?=$project->numbacker?></span></a></td>
            <td>
                <div class="progress progress-bar-danger">
                    <div class="progress-bar progress-bar-success" style="width: <?= (100* $project->total) /$project->goal ?>%" role="progressbar" aria-valuenow="<?=$project->total?>" aria-valuemin="0" aria-valuemax="<?=$project->goal?>">
                        <?= round((100* $project->total) /$project->goal , 2) ?>%
                    </div>
                </div>
                <?=number_format($project->total + 0, 0, ',', '.') . ' / ' . number_format($project->goal, 0, ',', '.')?>
            </td>
            <td><?=$project->deadline?></td>
            <td><?=$project->address . ', ' . (isset($province[$project->location]) ? $province[$project->location] : '')?></td>
            <td>
                <a class="view" title="View <?=$project->projectname?>" href="<?=site_url('admin/project/view/') . '/' . $project->projectid?>"><i style="font-size: 20px" class="entypo-search"></i></a>-
                <a class="edit" title="Edit <?=$project->projectname?>" href="<?=site_url('admin/project/edit/') . '/' . $project->projectid?>"><i style="font-size: 20px" class="entypo-pencil"></i></a>-
                <a title="Delete <?=$project->projectname?>" href="<?=site_url('admin/project/delete/') . '/' . $project->projectid?>" class="delete"><i style="font-size: 20px" class="entypo-cancel-circled"></i></a>
            </td>
        </tr>
        <?php
            endforeach;
        ?>
    </tbody>
</table>

<script>
    $(document).ready(function(){
        $("#listProject").dataTable({
            "sPaginationType": "bootstrap"
        });

        $(".delete").click(function(){
            if(confirm("Are you sure to delete this project?")){
                return true;
            }
            return false;
        })
    });
</script>